### ISSUE TITLE
Compteur ne change pas dans la version mobile

### ISSUE THREAD

**Issue by blirette** [webaquebec/webaquebec2016-splash#10]
Le compteur ne tourne pas dans la version mobile sous iOS8 / Safari. Seulement le nombre de chiffre change. Ça affiche donc 9 jours, 9 salles thématiques, 999 participants, 99 conférences, 9999 lunchs, etc.

**Comment by paulcote** [comment]
Weird ça fonctionne de mon côté. Je vais regarder ça.

**Comment by paulcote** [comment]
Peut-être une diff entre iOS 8 et 9
