### ISSUE TITLE
Corriger le lien de retour après inscription

### ISSUE THREAD

**Issue by blirette** [webaquebec/webaquebec2016-splash#11]
Corriger le lien qui ramène sur www.quebecnumerique.com lors de l'inscription à l'infolettre.

![image](https://cloud.githubusercontent.com/assets/1894507/9996875/3bade420-6057-11e5-9155-e772c95033ba.png)

**Comment by j15e** [comment]
C'est réglé pour le lien et j'ai indiqué Web à Québec plutôt que Québec Numérique pour éviter la confusion et j'ai même mis un peu de style!

![capture d ecran 2015-09-22 a 11 02 48](https://cloud.githubusercontent.com/assets/143380/10022179/7ce69082-6119-11e5-93d6-23053e002f64.png)
