### ISSUE TITLE
Apply sv4everybody on IE only

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-splash#13]
Ce script tag devrait aller dans un ie8 thingy

`<script type="text/javascript" src="/js/vendor/svg4everybody.ie8.min.js"></script>`

**Comment by paulcote** [comment]
Déja une issue d'ouvert pour ça : #2

**Comment by j15e** [comment]
Ah lol j'avais pas vu c'est un collègue qui m'a dit ça

**Comment by paulcote** [comment]
Et non en fait selon la doc de svg4everybody on le met pas dans une comment conditionnel vu qui s'applique aussi à d'autre browser que IE

**Comment by j15e** [comment]
Ah oki great, juste mêlant que ce soit .ie8 héhé

**Comment by paulcote** [comment]
Ouais comme mon collègue m'a dit : "C'est pas pour ie8, ça veux juste dire que le script supporte ie8" J'ai pas mal eu la même réaction que toi avant qui me dise ça.
