### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by paulcote** [webaquebec/webaquebec2016-splash#14]

**Comment by j15e** [comment]
J'avais un peu abandonné le projet mais si t'es game ça serait cool on peut l'ajouter plus tard

Je vais pas attendre ça pour le mettre en ligne pour envoyer l'infolettre de CFP

**Comment by paulcote** [comment]
On repassera pour l'an prochain, le splash est plus en ligne anyway.

**Comment by j15e** [comment]
Ya! :+1: Dream On
