### ISSUE TITLE
Traduction la rétroaction de soumission de courriel à l'infolettre

### ISSUE THREAD

**Issue by blirette** [webaquebec/webaquebec2016-splash#7]
Il faudrait traduire le texte de soumission de courriel à l'infolettre.

![image](https://cloud.githubusercontent.com/assets/1894507/9993715/259e4824-6047-11e5-8795-23bfe1cac8e7.png)

**Comment by blirette** [comment]
Même chose pour le courriel reçu (juste pour être certain de ne pas l'oublier).

![image](https://cloud.githubusercontent.com/assets/1894507/9996731/5f8c99dc-6056-11e5-8e06-5946eea22aea.png)

**Comment by paulcote** [comment]
@j15e Est-ce que tu va pouvoir regarder ça de ton côté ?
J'ai l'impression qui faut configurer de quoi dans Mailchimp. Il faut aussi un fichier js pour form pour la traduction. Je vais essayer de regarder ça mais si tu peux possiblement me fournir le code avec le fichier JS après avoir fait les configs dans Mailchimp ça serait bien aussi.

**Comment by blirette** [comment]
... ainsi que la gestion de mise à jour de nos informations (nom, prénom). ![image](https://cloud.githubusercontent.com/assets/1894507/9996842/0e8794b4-6057-11e5-8c4b-808cf5bcff28.png)

**Comment by j15e** [comment]
Tout est traduit maintenant :

![capture d ecran 2015-09-22 a 11 05 54](https://cloud.githubusercontent.com/assets/143380/10022275/f155de32-6119-11e5-8eee-83a3cd7b5812.png)
