### ISSUE TITLE
Réduire l'espace entre les paragraphes

### ISSUE THREAD

**Issue by blirette** [webaquebec/webaquebec2016-splash#8]
Il faudrait réduire l'espace entre les paragraphes dans la capture d'écran pour la version mobile.
![image](https://cloud.githubusercontent.com/assets/1894507/9993758/5e1fc312-6047-11e5-9099-cb841a114917.png)

**Comment by paulcote** [comment]
@blirette Est-ce possible d'avoir plus détails sur la plateforme (quel OS, quelle taille) ? 
Car je n'ai pas ce problème de mon côté.

Merci.

**Comment by j15e** [comment]
Moi ça le fait dans Chrome quand je rapetisse le cadre

**Comment by paulcote** [comment]
Ok ouais sur mobile ça fera pas vraiment ça. La première section s'ajuste avec l'hauteur de l'écran (vh) mais a un certain minimum (min-height). Donc à moins qu'on soit rendu avec des téléphone 25:9 ça devrait pas arriver.

**Comment by blirette** [comment]
Même chose, ça le fait sur Chrome lorsqu'on rapetisse la fenêtre. Ça n'apparaît en effet pas sous Safari iOS8.
